aws-tools:
  restart: always
  image: aws-tools
  hostname: aws-tools
  container_name: awt
  command: sh -c "while true; do sleep 60; done"
  volumes:
    - "~/.aws:/root/.aws"
    - "~/src:/opt/app/src"
  env_file:
    - env.dev
